### ISSUE TITLE
Document why ingested log lines can only be 64kb

### ISSUE THREAD

**Issue by paddycarver** [hashicorp/terraform-plugin-log#14]
### Does this documenation exist?

* [x] This is new documentation
* [ ] This is an enhancement to existing documentation

### Where would you expect to find this documentation?

* [ ] On terraform.io
* [x] In the GoDoc for this module
* [x] In this repo as a markdown file
* [ ] Somewhere else

#### Details

When ingesting log lines from the sink, those log lines can only be 64kb before overflowing that buffer. If they overflow that buffer, they're discarded. We should probably also write down that we picked that buffer size because "🤷‍♂️ that's what was in the go-plugin code we copied most the sink logic from".

**Comment by bookshelfdave** [comment]
We decided against using a sink.
